version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
          - "@chromatic-com/storybook"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "playwright"
      changesets:
        patterns:
          - "@changesets/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
